local c = require('windows-classic.palette')

local hl = vim.api.nvim_set_hl
local theme = {}

theme.set_highlights = function()
  -- Editor
  hl(0, "Normal", { fg = c.fg, bg = c.bg })
  hl(0, "SignColumn", { fg = c.blues.text, bg = c.window.bg })
  hl(0, "MsgArea", { fg = c.fg, bg = 'NONE' })
  hl(0, "ModeMsg", { fg = c.fg, bg = c.window.bg })
  hl(0, "MsgSeparator", { fg = c.fg, bg = c.bg })
  hl(0, "SpellBad", { fg = 'NONE', bg = 'NONE', sp = c.reds.error, undercurl = true })
  hl(0, "SpellCap", { fg = 'NONE', bg = 'NONE', sp = c.warn, undercurl = true })
  hl(0, "SpellLocal", { fg = 'NONE', bg = 'NONE', sp = c.info, underline = true })
  hl(0, "SpellRare", { fg = 'NONE', bg = 'NONE', sp = c.hint, underline = true })
  hl(0, "NormalNC", { fg = c.fg, bg = c.bg })
  hl(0, "Pmenu", { fg = c.window.fg, bg = c.window.bg })
  hl(0, "PmenuSel", { fg = c.select_fg, bg = c.select })
  hl(0, "WildMenu", { fg = c.select_fg, bg = c.select })
  hl(0, "LineNr", { fg = c.grays.text_disabled, bg = c.window.bg })
  hl(0, "CursorLineNr", { fg = c.blues.text, bg = 'NONE', bold = true, })
  hl(0, "Folded", { fg = c.grays.text_disabled, bg = c.grays.button_light })
  hl(0, "FoldColumn", { fg = c.grays.text_disabled, bg = c.window.bg })
  hl(0, "FloatBorder", { fg = c.window.border, bg = c.window.bg })
  hl(0, "FloatTitle", { fg = c.titlebar.active_fg, bg = c.titlebar.active_bg, bold = true })
  hl(0, "Whitespace", { fg = c.grays.button_shadow, bg = 'NONE' })
  hl(0, "VertSplit", { fg = c.window.border, bg = c.bg })
  hl(0, "CursorLine", { fg = 'NONE', bg = c.grays.button_light })
  hl(0, "CursorColumn", { fg = 'NONE', bg = c.grays.button_light })
  hl(0, "ColorColumn", { fg = 'NONE', bg = c.window.bg })
  hl(0, "NormalFloat", { fg = c.window.fg, bg = c.window.bg })
  hl(0, "Visual", { fg = c.select_fg, bg = c.select })
  hl(0, "VisualNOS", { fg = c.select_fg, bg = c.select })
  hl(0, "WarningMsg", { fg = c.warn, bg = c.bg })
  hl(0, "DiffText", { fg = 'NONE', bg = c.grays.button_light })
  hl(0, "DiffAdd", { fg = 'NONE', bg = "#c0ffc0" })
  hl(0, "DiffChange", { fg = 'NONE', bg = "#ffffc0" })
  hl(0, "DiffDelete", { fg = 'NONE', bg = "#ffc0c0" })
  hl(0, "PmenuSbar", { fg = 'NONE', bg = c.grays.button_face })
  hl(0, "PmenuThumb", { fg = 'NONE', bg = c.grays.button_shadow })
  hl(0, "Cursor", { fg = c.bg, bg = c.fg })
  hl(0, "Conceal", { fg = c.grays.text_disabled, bg = 'NONE' })
  hl(0, "Directory", { fg = c.blues.text, bg = 'NONE' })
  hl(0, "SpecialKey", { fg = c.blues.text_light, bg = 'NONE', bold = true })
  hl(0, "ErrorMsg", { fg = c.reds.error, bg = c.bg, bold = true })
  hl(0, "Search", { fg = c.select_fg, bg = c.select })
  hl(0, "IncSearch", { fg = c.select_fg, bg = c.select })
  hl(0, "CurSearch", { fg = c.fg, bg = c.yellow })
  hl(0, "Substitute", { fg = c.select_fg, bg = c.select })
  hl(0, "MoreMsg", { fg = c.greens.primary, bg = 'NONE' })
  hl(0, "Question", { fg = c.greens.primary, bg = 'NONE' })
  hl(0, "EndOfBuffer", { fg = c.grays.button_shadow, bg = 'NONE' })
  hl(0, "NonText", { fg = c.grays.button_shadow, bg = 'NONE' })
  hl(0, "TabLine", { fg = c.fg, bg = c.grays.button_face })
  hl(0, "TabLineSel", { fg = c.fg, bg = c.bg, bold = true })
  hl(0, "TabLineFill", { fg = 'NONE', bg = c.grays.button_face })
  hl(0, "WinSeparator", { fg = c.window.border, bg = 'NONE' })

  -- Syntax
  hl(0, "Comment", { fg = c.tokens.comment, bg = 'NONE', italic = false, })
  hl(0, "Variable", { fg = c.tokens.variable, bg = 'NONE' })
  hl(0, "String", { fg = c.tokens.string, bg = 'NONE' })
  hl(0, "Character", { fg = c.tokens.string, bg = 'NONE' })
  hl(0, "Number", { fg = c.tokens.number, bg = 'NONE' })
  hl(0, "Float", { fg = c.tokens.number, bg = 'NONE' })
  hl(0, "Boolean", { fg = c.tokens.number, bg = 'NONE' })
  hl(0, "Constant", { fg = c.tokens.variable, bg = 'NONE' })
  hl(0, "Type", { fg = c.tokens.type, bg = 'NONE' })
  hl(0, "Typedef", { fg = c.tokens.type, bg = 'NONE' })
  hl(0, "Function", { fg = c.tokens.func, bg = 'NONE' })
  hl(0, "Keyword", { fg = c.tokens.keyword, bg = 'NONE', bold = true })
  hl(0, "Conditional", { fg = c.tokens.conditional, bg = 'NONE', bold = true })
  hl(0, "Operator", { fg = c.fg, bg = 'NONE' })
  hl(0, "Include", { fg = c.tokens.include, bg = 'NONE' })
  hl(0, "Structure", { fg = c.tokens.type, bg = 'NONE' })
  hl(0, "Define", { fg = c.tokens.type, bg = 'NONE' })
  hl(0, "Macro", { fg = c.tokens.type, bg = 'NONE' })
  hl(0, "Debug", { fg = c.reds.error, bg = 'NONE' })
  hl(0, "Title", { fg = c.blues.text, bg = 'NONE', bold = true, })
  hl(0, "Delimiter", { fg = c.fg, bg = 'NONE' })
  hl(0, "SpecialComment", { fg = c.fg, bg = 'NONE' })
  hl(0, "Tag", { fg = c.blues.text, bg = 'NONE' })
  hl(0, "Bold", { fg = c.fg, bg = 'NONE', bold = true, })
  hl(0, "Italic", { fg = 'NONE', bg = 'NONE', italic = true, })
  hl(0, "Underlined", { fg = c.blues.text_light, bg = 'NONE', underline = true, })
  hl(0, "Todo", { fg = c.tokens.comment, bg = 'NONE', bold = true, })
  hl(0, "Error", { fg = c.reds.error, bg = 'NONE', bold = true, })
  hl(0, "Statement", { fg = c.tokens.statement, bg = 'NONE', bold = true })
  hl(0, "Identifier", { fg = c.fg, bg = 'NONE' })
  hl(0, "Special", { fg = c.tokens.special, bg = 'NONE' })

  -- StatusLine (classic Win95 taskbar style)
  hl(0, "StatusLine", { fg = c.fg, bg = c.grays.button_face })
  hl(0, "StatusLineNC", { fg = c.grays.text_disabled, bg = c.grays.button_face })

  -- QuickFix
  hl(0, "QuickFixLine", { fg = c.select_fg, bg = c.select })
  hl(0, "qfSeparator", { fg = c.grays.button_shadow, bg = "NONE" })
  hl(0, "qfFilename", { fg = c.blues.text, bg = "NONE" })
  hl(0, "qfLineNr", { fg = c.reds.primary, bg = "NONE" })
  hl(0, "qfError", { link = 'Error' })

  -- Bqf
  hl(0, "BqfPreviewBorder", { link = 'FloatBorder' })
  hl(0, "BqfPreviewRange", { link = 'Visual' })
  hl(0, "BqfSign", { fg = c.warn, bg = 'NONE' })

  -- Treesitter
  hl(0, "@comment", { fg = c.tokens.comment, bg = 'NONE', italic = false, })
  hl(0, "@none", { fg = 'NONE', bg = 'NONE' })
  hl(0, "@preproc", { link = 'PreProc' })
  hl(0, "@define", { link = 'Define' })
  hl(0, "@operator", { link = 'Operator' })
  hl(0, "@punctuation.delimeter", { link = 'Delimiter' })
  hl(0, "@punctuation.bracket", { link = 'Delimiter' })
  hl(0, "@punctuation.special", { fg = c.blues.text, bg = 'NONE' })
  hl(0, "@string", { link = 'String' })
  hl(0, "@string.regex", { link = 'String' })
  hl(0, "@string.escape", { link = 'SpecialChar' })
  hl(0, "@string.special", { link = 'SpecialChar' })
  hl(0, "@character", { link = 'Character' })
  hl(0, "@character.special", { link = 'SpecialChar' })
  hl(0, "@boolean", { link = 'Boolean' })
  hl(0, "@number", { link = 'Number' })
  hl(0, "@float", { link = 'Float' })
  hl(0, "@function", { link = 'Function' })
  hl(0, "@function.builtin", { link = 'Function' })
  hl(0, "@function.call", { link = 'Function' })
  hl(0, "@function.macro", { link = 'Macro' })
  hl(0, "@method", { link = 'Function' })
  hl(0, "@method.call", { link = 'Function' })
  hl(0, "@constructor", { link = '@type' })
  hl(0, "@parameter", { fg = c.fg, bg = 'NONE' })
  hl(0, "@variable.parameter", { fg = c.fg, bg = 'NONE' })
  hl(0, "@keyword", { link = 'Keyword' })
  hl(0, "@keyword.function", { link = 'Keyword' })
  hl(0, "@keyword.operator", { link = 'Keyword' })
  hl(0, "@keyword.return", { link = 'Include' })
  hl(0, "@keyword.repeat", { link = 'Include' })
  hl(0, "@keyword.coroutine", { link = 'Include' })
  hl(0, "@keyword.conditional", { link = 'Conditional' })
  hl(0, "@conditional", { link = 'Conditional' })
  hl(0, "@repeat", { link = 'Repeat' })
  hl(0, "@debug", { link = 'Debug' })
  hl(0, "@label", { link = 'Label' })
  hl(0, "@include", { link = 'Include' })
  hl(0, "@exception", { link = 'Exception' })
  hl(0, "@type", { link = 'Type' })
  hl(0, "@type.builtin", { link = 'Type' })
  hl(0, "@type.definition", { link = 'Typedef' })
  hl(0, "@type.qualifier", { link = 'Type' })
  hl(0, "@storageclass", { link = 'StorageClass' })
  hl(0, "@attribute", { link = 'PreProc' })
  hl(0, "@field", { fg = c.fg, bg = 'NONE' })
  hl(0, "@property", { fg = c.fg, bg = 'NONE' })
  hl(0, "@variable.member", { fg = c.fg, bg = 'NONE' })
  hl(0, "@variable", { link = 'Variable' })
  hl(0, "@variable.builtin", { fg = c.blues.text, bg = 'NONE' })
  hl(0, "@constant", { link = 'Constant' })
  hl(0, "@constant.builtin", { fg = c.blues.text, bg = 'NONE' })
  hl(0, "@constant.macro", { link = 'Macro' })
  hl(0, "@namespace", { link = 'Type' })
  hl(0, "@symbol", { link = 'Identifier' })
  hl(0, "@text", { link = 'None' })
  hl(0, "@text.strong", { link = 'Bold' })
  hl(0, "@text.emphasis", { link = 'Italic' })
  hl(0, "@text.underline", { link = 'Underlined' })
  hl(0, "@text.strike", { fg = 'NONE', bg = 'NONE', strikethrough = true, })
  hl(0, "@text.title", { link = 'Title' })
  hl(0, "@text.literal", { link = 'String' })
  hl(0, "@text.uri", { link = 'Underlined' })
  hl(0, "@text.math", { link = 'Special' })
  hl(0, "@text.environment", { link = 'Macro' })
  hl(0, "@text.environment.name", { link = 'Type' })
  hl(0, "@text.reference", { link = 'Constant' })
  hl(0, "@text.todo", { link = 'Todo' })
  hl(0, "@text.note", { link = 'SpecialComment' })
  hl(0, "@text.warning", { link = 'Todo' })
  hl(0, "@text.danger", { link = 'WarningMsg' })
  hl(0, "@tag", { link = 'Tag' })
  hl(0, "@tag.attribute", { fg = c.reds.primary, bg = 'NONE' })
  hl(0, "@tag.delimiter", { fg = c.grays.text_disabled, bg = 'NONE' })
  hl(0, "@lsp.type.comment", { link = '@comment' })
  hl(0, "@lsp.type.enum", { link = 'Type' })
  hl(0, "@lsp.type.interface", { link = 'Type' })
  hl(0, "@lsp.type.keyword", { link = 'Keyword' })
  hl(0, "@lsp.type.namespace", { link = '@namespace' })
  hl(0, "@lsp.type.parameter", { link = '@parameter' })
  hl(0, "@lsp.type.property", { link = '@property' })
  hl(0, "@lsp.type.variable", { link = '@variable' })
  hl(0, "@lsp.typemod.method.defaultLibrary", { link = '@function.builtin' })
  hl(0, "@lsp.typemod.function.defaultLibrary", { link = '@function.builtin' })
  hl(0, "@lsp.typemod.variable.defaultLibrary", { link = '@variable.builtin' })
  hl(0, "@lsp.typemod.operator.injected", { link = '@operator' })
  hl(0, "@lsp.typemod.string.injected", { link = '@string' })
  hl(0, "@lsp.typemod.variable.injected", { link = '@variable' })
  hl(0, "LspCodeLens", { fg = c.grays.text_disabled, bg = 'NONE', italic = true })
  hl(0, "LspCodeLensSeparator", { fg = c.grays.text_disabled, bg = 'NONE', italic = true })

  -- LSP
  hl(0, "LspInlayHint", { fg = c.grays.text_disabled, bg = 'NONE' })
  hl(0, "DiagnosticUnnecessary", { fg = c.grays.text_disabled, bg = 'NONE' })
  hl(0, "DiagnosticHint", { fg = c.hint, bg = 'NONE' })
  hl(0, "DiagnosticInfo", { fg = c.info, bg = 'NONE' })
  hl(0, "DiagnosticWarn", { fg = c.warn, bg = 'NONE' })
  hl(0, "DiagnosticError", { fg = c.error, bg = 'NONE' })
  hl(0, "DiagnosticOther", { fg = c.other, bg = 'NONE' })
  hl(0, "DiagnosticSignHint", { fg = c.hint, bg = c.window.bg })
  hl(0, "DiagnosticSignInfo", { fg = c.info, bg = c.window.bg })
  hl(0, "DiagnosticSignWarn", { fg = c.warn, bg = c.window.bg })
  hl(0, "DiagnosticSignError", { fg = c.error, bg = c.window.bg })
  hl(0, "DiagnosticSignOther", { fg = c.other, bg = c.window.bg })
  hl(0, "DiagnosticSignWarning", { fg = c.warn, bg = c.window.bg })
  hl(0, "DiagnosticFloatingHint", { link = 'DiagnosticHint' })
  hl(0, "DiagnosticFloatingInfo", { link = 'DiagnosticInfo' })
  hl(0, "DiagnosticFloatingWarn", { link = 'DiagnosticWarn' })
  hl(0, "DiagnosticFloatingError", { link = 'DiagnosticError' })
  hl(0, "DiagnosticSignInformation", { link = 'DiagnosticInfo' })
  hl(0, "DiagnosticUnderlineHint", { fg = 'NONE', bg = 'NONE', sp = c.hint, undercurl = true, })
  hl(0, "DiagnosticUnderlineInfo", { fg = 'NONE', bg = 'NONE', sp = c.info, undercurl = true, })
  hl(0, "DiagnosticUnderlineWarn", { fg = 'NONE', bg = 'NONE', sp = c.warn, undercurl = true, })
  hl(0, "DiagnosticUnderlineError", { fg = 'NONE', bg = 'NONE', sp = c.error, undercurl = true, })

  -- MatchParen
  hl(0, "MatchWord", { fg = 'NONE', bg = c.grays.button_light })
  hl(0, "MatchWordCur", { fg = 'NONE', bg = c.grays.button_light })
  hl(0, "MatchParen", { fg = 'NONE', bg = c.grays.button_light, bold = true })
  hl(0, "MatchParenCur", { fg = 'NONE', bg = c.grays.button_light })

  -- IndentBlankline
  hl(0, "IndentBlanklineChar", { fg = c.indent, bg = 'NONE' })
  hl(0, "IndentBlanklineContextChar", { fg = c.indent_active, bg = 'NONE' })
  hl(0, "IndentBlanklineContextStart", { fg = 'NONE', bg = 'NONE', underline = true, })

  -- Telescope
  hl(0, "TelescopeSelection", { fg = c.select_fg, bg = c.select })
  hl(0, "TelescopeSelectionCaret", { fg = c.select_fg, bg = c.select })
  hl(0, "TelescopeMatching", { fg = c.reds.error, bg = 'NONE', bold = true, })
  hl(0, "TelescopeBorder", { fg = c.window.border, bg = c.window.bg })
  hl(0, "TelescopeNormal", { fg = c.window.fg, bg = c.window.bg })
  hl(0, "TelescopePromptTitle", { fg = c.titlebar.active_fg, bg = c.titlebar.active_bg, bold = true })
  hl(0, "TelescopePromptPrefix", { fg = c.window.fg, bg = 'NONE' })
  hl(0, "TelescopeResultsTitle", { fg = c.titlebar.active_fg, bg = c.titlebar.active_bg, bold = true })
  hl(0, "TelescopePreviewTitle", { fg = c.titlebar.active_fg, bg = c.titlebar.active_bg, bold = true })
  hl(0, "TelescopePromptCounter", { fg = c.window.fg, bg = 'NONE' })

  -- Git
  hl(0, "GitSignsAdd", { fg = c.gitsigns_add, bg = c.window.bg })
  hl(0, "GitSignsChange", { fg = c.gitsigns_change, bg = c.window.bg })
  hl(0, "GitSignsDelete", { fg = c.gitsigns_delete, bg = c.window.bg })

  -- Cmp
  hl(0, "CmpItemAbbrDeprecated", { fg = c.grays.text_disabled, bg = 'NONE', strikethrough = true })
  hl(0, "CmpItemAbbr", { fg = c.window.fg, bg = 'NONE' })
  hl(0, "CmpItemAbbrMatch", { fg = c.blues.text, bg = 'NONE', bold = true })
  hl(0, "CmpItemAbbrMatchFuzzy", { fg = c.blues.text_light, bg = 'NONE' })
  hl(0, "CmpDocumentation", { fg = c.window.fg, bg = 'NONE' })
  hl(0, "CmpDocumentationBorder", { fg = c.window.fg, bg = 'NONE' })
  hl(0, "CmpItemKind", { fg = c.blues.text, bg = 'NONE' })
  -- Functions/Methods - purple
  hl(0, "CmpItemKindFunction", { fg = c.purples.text, bg = 'NONE' })
  hl(0, "CmpItemKindMethod", { fg = c.purples.text, bg = 'NONE' })
  hl(0, "CmpItemKindConstructor", { fg = c.purples.text, bg = 'NONE' })
  -- Types/Classes - blue
  hl(0, "CmpItemKindClass", { fg = c.blues.text, bg = 'NONE' })
  hl(0, "CmpItemKindEnum", { fg = c.blues.text, bg = 'NONE' })
  hl(0, "CmpItemKindInterface", { fg = c.blues.text, bg = 'NONE' })
  hl(0, "CmpItemKindStruct", { fg = c.blues.text, bg = 'NONE' })
  hl(0, "CmpItemKindTypeParameter", { fg = c.blues.text, bg = 'NONE' })
  -- Variables/Fields
  hl(0, "CmpItemKindVariable", { fg = c.fg, bg = 'NONE' })
  hl(0, "CmpItemKindField", { fg = c.fg, bg = 'NONE' })
  hl(0, "CmpItemKindProperty", { fg = c.fg, bg = 'NONE' })
  hl(0, "CmpItemKindEnumMember", { fg = c.blues.text_light, bg = 'NONE' })
  -- Constants - maroon
  hl(0, "CmpItemKindConstant", { fg = c.reds.primary, bg = 'NONE' })
  -- Keywords
  hl(0, "CmpItemKindKeyword", { fg = c.tokens.keyword, bg = 'NONE' })
  hl(0, "CmpItemKindOperator", { fg = c.fg, bg = 'NONE' })
  -- Modules/Namespaces
  hl(0, "CmpItemKindModule", { fg = c.reds.light, bg = 'NONE' })
  -- Values
  hl(0, "CmpItemKindValue", { fg = c.reds.primary, bg = 'NONE' })
  hl(0, "CmpItemKindUnit", { fg = c.reds.primary, bg = 'NONE' })
  -- Text/Snippets - green
  hl(0, "CmpItemKindText", { fg = c.greens.text, bg = 'NONE' })
  hl(0, "CmpItemKindSnippet", { fg = c.greens.primary, bg = 'NONE' })
  -- Files/Folders
  hl(0, "CmpItemKindFile", { fg = c.grays.text_disabled, bg = 'NONE' })
  hl(0, "CmpItemKindFolder", { fg = c.folder, bg = 'NONE' })
  -- Events
  hl(0, "CmpItemKindEvent", { fg = c.warn, bg = 'NONE' })
  -- References
  hl(0, "CmpItemKindReference", { fg = c.reds.primary, bg = 'NONE' })
  hl(0, "CmpItemKindColor", { fg = c.purples.text, bg = 'NONE' })

  -- Blink.cmp
  -- Menu & UI
  hl(0, "BlinkCmpMenu", { fg = c.window.fg, bg = c.window.bg })
  hl(0, "BlinkCmpMenuBorder", { fg = c.window.border, bg = c.window.bg })
  hl(0, "BlinkCmpMenuSelection", { fg = c.select_fg, bg = c.select })
  hl(0, "BlinkCmpScrollBarThumb", { fg = 'NONE', bg = c.grays.button_shadow })
  hl(0, "BlinkCmpScrollBarGutter", { fg = 'NONE', bg = c.grays.button_face })
  -- Labels
  hl(0, "BlinkCmpLabel", { fg = c.window.fg, bg = 'NONE' })
  hl(0, "BlinkCmpLabelDeprecated", { fg = c.grays.text_disabled, bg = 'NONE', strikethrough = true })
  hl(0, "BlinkCmpLabelMatch", { fg = c.blues.text, bg = 'NONE', bold = true })
  hl(0, "BlinkCmpLabelDetail", { fg = c.grays.text_disabled, bg = 'NONE' })
  hl(0, "BlinkCmpLabelDescription", { fg = c.grays.text_disabled, bg = 'NONE' })
  -- Kind (default)
  hl(0, "BlinkCmpKind", { fg = c.blues.text, bg = 'NONE' })
  -- Functions/Methods - purple
  hl(0, "BlinkCmpKindFunction", { fg = c.purples.text, bg = 'NONE' })
  hl(0, "BlinkCmpKindMethod", { fg = c.purples.text, bg = 'NONE' })
  hl(0, "BlinkCmpKindConstructor", { fg = c.purples.text, bg = 'NONE' })
  -- Types/Classes - blue
  hl(0, "BlinkCmpKindClass", { fg = c.blues.text, bg = 'NONE' })
  hl(0, "BlinkCmpKindEnum", { fg = c.blues.text, bg = 'NONE' })
  hl(0, "BlinkCmpKindInterface", { fg = c.blues.text, bg = 'NONE' })
  hl(0, "BlinkCmpKindStruct", { fg = c.blues.text, bg = 'NONE' })
  hl(0, "BlinkCmpKindTypeParameter", { fg = c.blues.text, bg = 'NONE' })
  -- Variables/Fields
  hl(0, "BlinkCmpKindVariable", { fg = c.fg, bg = 'NONE' })
  hl(0, "BlinkCmpKindField", { fg = c.fg, bg = 'NONE' })
  hl(0, "BlinkCmpKindProperty", { fg = c.fg, bg = 'NONE' })
  hl(0, "BlinkCmpKindEnumMember", { fg = c.blues.text_light, bg = 'NONE' })
  -- Constants - maroon
  hl(0, "BlinkCmpKindConstant", { fg = c.reds.primary, bg = 'NONE' })
  -- Keywords
  hl(0, "BlinkCmpKindKeyword", { fg = c.tokens.keyword, bg = 'NONE' })
  hl(0, "BlinkCmpKindOperator", { fg = c.fg, bg = 'NONE' })
  -- Modules/Namespaces
  hl(0, "BlinkCmpKindModule", { fg = c.reds.light, bg = 'NONE' })
  -- Values
  hl(0, "BlinkCmpKindValue", { fg = c.reds.primary, bg = 'NONE' })
  hl(0, "BlinkCmpKindUnit", { fg = c.reds.primary, bg = 'NONE' })
  -- Text/Snippets - green
  hl(0, "BlinkCmpKindText", { fg = c.greens.text, bg = 'NONE' })
  hl(0, "BlinkCmpKindSnippet", { fg = c.greens.primary, bg = 'NONE' })
  -- Files/Folders
  hl(0, "BlinkCmpKindFile", { fg = c.grays.text_disabled, bg = 'NONE' })
  hl(0, "BlinkCmpKindFolder", { fg = c.folder, bg = 'NONE' })
  -- Events
  hl(0, "BlinkCmpKindEvent", { fg = c.warn, bg = 'NONE' })
  -- References
  hl(0, "BlinkCmpKindReference", { fg = c.reds.primary, bg = 'NONE' })
  hl(0, "BlinkCmpKindColor", { fg = c.purples.text, bg = 'NONE' })
  -- Documentation & Signature
  hl(0, "BlinkCmpDoc", { fg = c.window.fg, bg = c.window.bg })
  hl(0, "BlinkCmpDocBorder", { fg = c.window.border, bg = c.window.bg })
  hl(0, "BlinkCmpDocSeparator", { fg = c.grays.button_shadow, bg = c.window.bg })
  hl(0, "BlinkCmpDocCursorLine", { fg = c.select_fg, bg = c.select })
  hl(0, "BlinkCmpGhostText", { fg = c.grays.text_disabled, bg = 'NONE' })
  hl(0, "BlinkCmpSignatureHelp", { fg = c.window.fg, bg = c.window.bg })
  hl(0, "BlinkCmpSignatureHelpBorder", { fg = c.window.border, bg = c.window.bg })
  hl(0, "BlinkCmpSignatureHelpActiveParameter", { fg = c.select_fg, bg = c.select, bold = true })

  -- Typescript/JSX
  hl(0, "@lsp.type.interface.typescriptreact", { fg = c.tokens.jsx, bg = 'NONE' })
  hl(0, "@lsp.type.namespace.typescriptreact", { fg = c.tokens.jsx, bg = 'NONE' })
  hl(0, "typescriptArrowFuncArg", { fg = c.fg, bg = 'NONE' })
  hl(0, "typescriptCall", { fg = c.fg, bg = 'NONE' })
  hl(0, "typescriptTemplateSB", { fg = c.fg, bg = 'NONE' })
  hl(0, "typescriptBraces", { fg = c.fg, bg = 'NONE' })
  hl(0, "@tag.tsx", { fg = c.tokens.jsx, bg = 'NONE' })
  hl(0, "@tag.jsx", { fg = c.tokens.jsx, bg = 'NONE' })

  -- Lazy
  hl(0, "LazyButton", { fg = c.fg, bg = c.grays.button_face })
  hl(0, "LazyButtonActive", { fg = c.select_fg, bg = c.select })
  hl(0, "LazyComment", { link = 'Comment' })
  hl(0, "LazyH1", { fg = c.titlebar.active_fg, bg = c.titlebar.active_bg, bold = true, })

  -- Mason
  hl(0, "MasonHeader", { link = "LazyH1" })
  hl(0, "MasonMutedBlock", { link = "LazyButton" })
  hl(0, "MasonHighlightBlock", { link = "LazyButtonActive" })
end

return theme
